delimiter = "####"
DIALOGS = {
    'ERROR': 'Sorry some error occurred',
    'START': "Alright, hold onto your horseshoes and strap on your thinking cap, folks, because we're diving headfirst into a realm where mysteries are as thick as grandma's gravy, and our leading lady is one determined dynamo. Meet Eleanor, a spitfire of a dame with a nose for trouble and a heart full of moxie. She ain't your average damsel in distress, oh no. Eleanor's got more curiosity than a cat in a curiosity shop, and she's packing enough wits to make a genius blush. Born in a blink-and-you'll-miss-it village, this gal's upbringing was soaked in tales of her old man's legendary escapades. But here's the kicker the guy vanished into thin air when she was knee-high to a grasshopper. Poof! Gone without a trace.Now, if that was your average garden variety sob story, we'd be swapping handkerchiefs and passing around the tissues. But Eleanor, she ain't about that sniffling life. Nope, she's been sweating buckets, training harder than a squirrel in a coffee shop, and honing her combat skills like a blacksmith forging a sword in the fires of determination.But that ain't the half of it! This gal's got a mind sharper than a tack and a knack for cracking cryptic codes that'd give even the Sphinx a run for its riddles. She's got an eidetic memory, which means she remembers things with the clarity of a mosquito trapped in amber. Plus, she's got a sixth sense for deciphering ancient languages that have stumped scholars for centuries.You'd think she'd be all business and no play, right? Wrong! Eleanor's catchphrase is as sassy as a cat with a canary feather stuck between its teeth: 'Adventure awaits, and I'm ready to uncover the secrets of the past!' She's got more enthusiasm than a kid in a candy store, and she's got the skills to back up her bravado.So buckle up, dear players, 'cause Eleanor's on a mission. She's gonna follow in her father's footsteps, unearth the truth, and maybe even have a laugh or two along the way. Get ready to navigate treacherous terrain, decipher ancient puzzles, and kick a whole lot of proverbial butt, all while Eleanor struts her stuff and takes names. This ain't your grandma's bedtime story – it's a whirlwind of wit, action, and a dash of that good ol' Eleanor charm. Let's dive in and make history, folks!",
    'narrator_boss_flame': "Hold onto your sunhats and prepare to sizzle, because our intrepid player is about to waltz their way into the scorching desert. And what do we have here? Oh, just a giant, fiery inferno hanging out in a stone circle like it's roasting marshmallows on a cosmic campfire. But don't let those cozy vibes fool you, folks. This ain't no friendly ghost story by the firelight. Nope, this blazing behemoth is hotter than a dragon's sneeze and twice as spicy. Legend has it that this fire started as a mere spark, a twinkle in the desert's eye, but it grew and grew until it became a full-blown inferno with an attitude to match. This ain't your run-of-the-mill campfire gone wild, though. Oh no, this fire's got a beef, and it's not with marshmallows. No, this living conflagration is fuming over centuries of desert neglect and disrespect. Humans have been traipsing through its dunes, leaving their trash behind like they're at some kind of mystical picnic. Well, this fire's had enough, and it's decided to burn its frustration right into the sands. Now, the desert quivers with anticipation as you draw closer to this molten monstrosity. The air shimmers, the sand crackles, and the sky looks like it's about to join in on the fiery fiesta. But hold up, player, because you're not one to be barbecued without a fight. You've braved haunted forests, outsmarted mischievous sprites, and even pulled off a daring daylight robbery (in the name of justice, of course). You've got a trusty blade at your side and a backpack full of potions that would make an alchemist jealous. So, as you step into that stone circle, remember that you're not just facing a fire – you're squaring off against an elemental tantrum with a grudge. So, slap on some SPF infinity sunscreen, tighten your bootstraps, and get ready to dance with the devil – or, you know, the desert's vengeful temper tantrum. Will you douse this fiery feud and bring a little chill to the desert's wildest party? Or will you end up as crispy as a desert cactus in July? Get ready to find out, because the heat is on, and it's time to show this blazing boss who's really in control of the thermostat!",
    'narrator_boss_spirit': "Well, well, well, look who's wandered into the enchanted woods! It's our fearless player, ready to take on whatever the mystical forest has to throw their way. But wait, what's that looming in the distance? Oh, just a giant spirit chilling in a stone circle, like it's waiting for a round of mystical bingo or something. But this ain't your grandma's bingo night, folks. No, siree. This towering titan of the supernatural is here to give you a run for your potions. Legend has it that this spirit was once a guardian of the woods, keeping all the creepy crawlies and over-enthusiastic lumberjacks at bay. But, you know, spirits and their dramatic career changes. Rumor has it, this spirit got a little miffed at the way humans were treating its leafy domain. Chopping down trees, building log cabins, and leaving their empty snack wrappers everywhere. The nerve! So, this foresty phantom decided to take matters into its own, uh, ethereal hands. Now, it's all vines, leaves, and supernatural sass as it guards its turf with the ferocity of a mama bear protecting her cubs. The trees sway, the wind whispers secrets, and the ground practically vibrates with anticipation. This ain't just a boss battle, it's a showdown with Mother Nature's cranky alter ego.But fear not, dear player, for you've got a few tricks up your sleeves too. You've been through thick and thin, bashed a few goblins, solved some ancient riddles, and heck, you even managed to out-dance a mischievous forest sprite last week. You're no rookie when it comes to dishing out the digital pain. So, take a deep breath, tighten that grip on your enchanted sword, and get ready to dance the dance of destiny with this colossal spirit. Will you unravel the secrets that turned it from guardian to ghostly grump? Or will you end up as just another gust of wind in its leafy repertoire? Get ready to find out, because the stage is set, the stones are singing, and the showdown of the century is about to go down in these mystical woods!",
    'narrator_boss_frog': "Hold onto your lily pads, ladies and gents, because we're about to dive into a swampy saga that's muckier than a pig in a puddle! Our intrepid player is wading their way towards a showdown with a gang of red giant frogs that'll have you croaking with both fear and laughter. Picture this: you're in a murky swamp, where the air is thick with mist and the ground is squelchier than a jellybean on a trampoline. And what do we have here, lurking among the reeds and eerie graveyard vibes? A group of red giant frogs, and these amphibious behemoths are ready to party like it's the end of the world – which, in their slimy swampy minds, it might as well be. Now, these aren't your run-of-the-mill frogs that you might find hopping around a pond. No, these are frogs with a flair for the dramatic, a taste for mischief, and a size that would make even the hungriest stork think twice. They're the kings and queens of this swampy domain, and they're not about to let anyone – human or otherwise – mess with their slimy sovereignty. But here's the twist, my fearless player: these frogs aren't just here to ribbit and chill. Oh no, they've got a bone to pick, and it's not the kind you'd find in a swampy graveyard. See, the spirits of this murky marsh have been whispering tales of a legendary treasure hidden deep within their watery realm. And these frogs, well, they're convinced it's their ticket to fame, fortune, and maybe even a cameo in a fairy tale or two So, as you approach their stomping – or should I say, hopping – grounds, the air practically buzzes with a mix of anticipation and froggy pheromones. The mist swirls like a curtain rising on nature's quirkiest drama, and the croaking symphony reaches a crescendo fit for a royal court of frogs. But hold onto your boots, dear player, because you're no tadpole in this pond. You've vanquished goblins, outwitted witches, and once negotiated a truce between two quarreling mountain goats (they were surprisingly articulate). You've got a sword that's sharper than a frog's tongue and a heart that's as brave as a frog facing a stork – maybe braver. So, adjust your swamp goggles, check your anti-slime armor, and prepare to hop into the fray. Will you give these regal frogs a run for their lily pads, unmask the mystery of the legendary treasure, and come out on top in this amphibious adventure? Or will you end up as just another pawn in their slimy game? Get ready to leap into action, because the frog fiesta is about to begin, and it's bound to be a ribbiting good time!",
    'narrator_boss_raccoon': "Hold onto your cherry blossoms, folks, because we're about to introduce you to a boss battle that's as dark as a moonless night and as cheeky as a raccoon rummaging through your trash at 3 AM. Our valiant player is venturing onto an island draped in the delicate beauty of blooming cherry trees, but don't let the picturesque scene fool you. There's a giant dark raccoon on the loose, and it's got more tricks up its furry sleeves than a magician at a squirrel convention. Imagine this: you're on an island, a place so serene that even the birds tip-toe around not to disturb the tranquility. And smack-dab in the middle of this picturesque paradise, you've got a giant raccoon that's blacker than the heart of a supervillain and twice as mischievous. This ain't your average backyard bandit, oh no. This raccoon is like the kingpin of chaos, and it's taken over the island like a fur-covered overlord. Now, you might be thinking, 'What's a raccoon doing on an island of cherry blossoms?' Well, buckle up, because this isn't your typical tail... uh, I mean, tale. Turns out, this raccoon got a taste for the mystical, and it's been munching on cherry blossoms that are rumored to grant untold power to whoever consumes them. Yep, you heard that right. We've got a raccoon that's traded in its trash heap for a cherry tree buffet, and it's juiced up on more power than a lightning bolt during a thunderstorm. But that's not all, my daring player. This raccoon has developed a taste for drama too. It's been causing cherry petals to rain down like a confetti cannon on a sugar high, and the island's once-peaceful residents are caught in the crossfire of its dark and flowery reign. As you approach the heart of the island, the air is heavy with the scent of cherry blossoms and the anticipation of a showdown that's been a long time coming. The trees sway in the breeze, the petals whirl like miniature tornadoes, and the whole place feels like a fairy tale gone rogue. But don't go mistaking this raccoon for some fluffy pushover, dear player. You've battled dragons, outwitted warlocks, and once talked a giant into taking up knitting (very therapeutic, by the way). You've got a sword that's as sharp as your wit and a heart that's as fierce as a mama bear protecting her cubs. So, polish your sword, adjust your armor, and get ready to tango with this oversized raccoon of darkness. Will you put a stop to its flower-powered rampage, reveal the secrets of the mystical cherry blossoms, and bring back tranquility to this island paradise? Or will you end up as just another petal in its chaotic bouquet? Get ready to blossom into action, because the raccoon ruckus is about to commence, and it's bound to be a bloomin' good time!",
    'narrator_boss_winter_raccoon': "Well, well, well, look who's trudging through the snow like a determined yeti with a bone to pick! Our valiant player is about to face a furry frenzy like no other – a gang of giant raccoons with an attitude as frosty as the snow beneath your boots. Picture this: you're in a snow desert, a place so cold that even the penguins are packing their bags and heading for the equator. But in the midst of this icy wasteland, a pack of raccoons has decided to set up shop. Now, these aren't your average, run-of-the-mill raccoons that go dumpster diving for stale pizza crusts. Oh no, these are some hefty hooligans, with paws the size of snowshoes and teeth as sharp as icicles. Why, you ask, would these raccoons brave the frozen tundra instead of cozying up in some forest den? Well, word has it that these frosty furballs have a thing for shiny stuff. And guess what's shinier than a disco ball at a laser light show? Your precious inventory, that's what! Yep, these raccoons are all about the bling. They've been raiding villages, stealing treasure, and generally causing more havoc than a toddler in a china shop. It's like Ocean's Eleven meets Ice Age, and these raccoons are the fur-covered ringleaders. But here's the twist – they're not just in it for the loot. No, these critters are smart, and they've got an agenda as cold as the snow they're hoarding. They're hatching a plan to dominate the snow desert, establish a raccoon dynasty, and perhaps start a raccoon-themed casino. Okay, maybe not that last part, but you get the idea. As you get closer to their hideout, the air practically crackles with mischief. Snowflakes fall like confetti from the sky, and the wind whispers tales of raccoon heists and snowball fights. But you, dear player, you're no stranger to a challenge. You've outwitted trolls, outsmarted wizards, and once talked a dragon into doing your laundry (long story). So, tighten your scarf, double-check your glove situation, and prepare to face off against these frosty bandits. Will you outfox the foxes, out-raccoon the raccoons, and emerge victorious from this chilly showdown? Or will you end up as their unwilling snowball target? Get ready to find out, because the raccoon ruckus is about to commence, and it's bound to be a fur-tastic adventure!",
    'boss_flame': 'Time to fight first boss',
    'boss_spirit': 'Time to fight secound boss',
    'boss_frog': 'Time to fight third boss',
    'boss_raccoon': 'Time to fight first boss',
    'boss_winter_raccoon': "",
    'END': 'It is the end of the game. Thanks for playing',
    'TEST': 'Hello, my name is Jan Cena and I am the strongest boss in this game you will meet Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tellus in hac habitasse platea dictumst vestibulum rhoncus. Leo vel orci porta non pulvinar neque laoreet suspendisse. Scelerisque viverra mauris in aliquam. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim. Diam vulputate ut pharetra sit amet aliquam id diam maecenas. Consectetur a erat nam at lectus. Et netus et malesuada fames ac turpis egestas. Egestas diam in arcu cursus euismod quis. Consequat ac felis donec et odio pellentesque. Semper feugiat nibh sed pulvinar proin gravida. Nulla pharetra diam sit amet nisl. Porttitor lacus luctus accumsan tortor posuere ac ut consequat semper. Nisi vitae suscipit tellus mauris a. Euismod elementum nisi quis eleifend quam adipiscing. Iaculis at erat pellentesque adipiscing commodo elit at. Netus et malesuada fames ac. Lacus luctus accumsan tortor posuere ac ut consequat semper. Facilisis volutpat est velit egestas dui. Dolor magna eget est lorem. Integer vitae justo eget magna fermentum. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Faucibus in ornare quam viverra orci. Mauris in aliquam sem fringilla. Ac turpis egestas integer eget aliquet nibh praesent. Massa tempor nec feugiat nisl pretium. Congue eu consequat ac felis donec et odio pellentesque diam. Viverra orci sagittis eu volutpat odio. Risus nec feugiat in fermentum. Blandit aliquam etiam erat velit scelerisque in dictum. Suspendisse faucibus interdum posuere lorem ipsum dolor. Massa tincidunt nunc pulvinar sapien et ligula. Diam phasellus vestibulum lorem sed risus. Nisi lacus sed viverra tellus in hac habitasse. Lectus magna fringilla urna porttitor rhoncus dolor purus non enim.'
}

boss = ''
atributes = "atributes= {\
    'name':'',\
    'gender':'',\
    'age':'',\
    'motivation':'',\
    'life_story':'',\
    'catch_phrase':''\
    }"

characters = {
    "main_character": {
                        "name": "Eleanor",
                        "gender": "Female",
                        "age": "27",
                        "motivation": "To uncover the truth behind her father's mysterious disappearance.",
                        "life_story": "Born in a small village, Eleanor grew up hearing stories of her father's \
                            legendary adventures as an explorer. He vanished without a trace when she was just a \
                                child. Determined to follow in his footsteps and find out what happened, Eleanor \
                                    has trained tirelessly in combat and survival skills.",
                        "catch_phrase": "Adventure awaits, and I'm ready to uncover the secrets of the past!"
                    },
    "boss_flame":"",
    "boss_spirit":"",
    "boss_frog":"",
    "boss_raccoon":""
}

boss_description = {
    'giant_spirit': "giant spitit located in the woods in circle made of stone",
    'giant_flame': "giant flame located on a desert in a circle made of stone",
    'giant_raccoons': "group of giant raccoons located on a snow desert",
    'giant_raccoon': "giant dark raccoon located on an island with blooming cherry trees",
    'giant_frog': "group of red giant frogs located near swamp and graveyard "
}

get_main_character = f"Your task is to create atributes of the main character of the computer RPG game with given in triple backticks atributes names \
                        Your answer should be provided in json format in the same order as it was provided to you, provide only the filled json file dont \
                            write anything else only json, here are the atributtes ### \
                        {atributes}###"

start_prompt = f"you are a narrator in a computer single player rpg game, your narrating style is provocative and at the same\
                time funny (something like deathpool). make an introductin to this game here are information about main character {characters['main_character']}"

# boss_narration_prompt = f"you are a narrator in a computer single player rpg game, your narrating style is provocative and at the same time funny (something like deathpool). \
#     The main player is coming close to fight with next boss which will be {boss_description[boss]} your task is to introduce player with who he will fight and present \
#     some story about the boss. It is not fight yet"
                

