DIALOGS = {
    'ERROR': 'Sorry some error occurred',
    'START': "Alright, hold onto your horseshoes and strap on your thinking cap, folks, because we're diving headfirst into a realm where mysteries are as thick as grandma's gravy, and our leading lady is one determined dynamo. Meet Eleanor, a spitfire of a dame with a nose for trouble and a heart full of moxie. She ain't your average damsel in distress, oh no. Eleanor's got more curiosity than a cat in a curiosity shop, and she's packing enough wits to make a genius blush. Born in a blink-and-you'll-miss-it village, this gal's upbringing was soaked in tales of her old man's legendary escapades. But here's the kicker the guy vanished into thin air when she was knee-high to a grasshopper. Poof! Gone without a trace.Now, if that was your average garden variety sob story, we'd be swapping handkerchiefs and passing around the tissues. But Eleanor, she ain't about that sniffling life. Nope, she's been sweating buckets, training harder than a squirrel in a coffee shop, and honing her combat skills like a blacksmith forging a sword in the fires of determination.But that ain't the half of it! This gal's got a mind sharper than a tack and a knack for cracking cryptic codes that'd give even the Sphinx a run for its riddles. She's got an eidetic memory, which means she remembers things with the clarity of a mosquito trapped in amber. Plus, she's got a sixth sense for deciphering ancient languages that have stumped scholars for centuries.You'd think she'd be all business and no play, right? Wrong! Eleanor's catchphrase is as sassy as a cat with a canary feather stuck between its teeth: 'Adventure awaits, and I'm ready to uncover the secrets of the past!' She's got more enthusiasm than a kid in a candy store, and she's got the skills to back up her bravado.So buckle up, dear players, 'cause Eleanor's on a mission. She's gonna follow in her father's footsteps, unearth the truth, and maybe even have a laugh or two along the way. Get ready to navigate treacherous terrain, decipher ancient puzzles, and kick a whole lot of proverbial butt, all while Eleanor struts her stuff and takes names. This ain't your grandma's bedtime story – it's a whirlwind of wit, action, and a dash of that good ol' Eleanor charm. Let's dive in and make history, folks!",
    'narrator_boss_flame': 'Time to fight first boss',
    'narrator_boss_spirit': 'Time to fight secound boss',
    'narrator_boss_frog': 'Time to fight third boss',
    'narrator_boss_raccoon': 'Time to fight third boss',
    'boss_flame': 'Time to fight first boss',
    'boss_spirit': 'Time to fight secound boss',
    'boss_frog': 'Time to fight third boss',
    'boss_raccoon': 'Time to fight first boss',
    'END': 'It is the end of the game. Thanks for playing',
    'TEST': 'Hello, my name is Jan Cena and I am the strongest boss in this game you will meet Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tellus in hac habitasse platea dictumst vestibulum rhoncus. Leo vel orci porta non pulvinar neque laoreet suspendisse. Scelerisque viverra mauris in aliquam. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim enim. Diam vulputate ut pharetra sit amet aliquam id diam maecenas. Consectetur a erat nam at lectus. Et netus et malesuada fames ac turpis egestas. Egestas diam in arcu cursus euismod quis. Consequat ac felis donec et odio pellentesque. Semper feugiat nibh sed pulvinar proin gravida. Nulla pharetra diam sit amet nisl. Porttitor lacus luctus accumsan tortor posuere ac ut consequat semper. Nisi vitae suscipit tellus mauris a. Euismod elementum nisi quis eleifend quam adipiscing. Iaculis at erat pellentesque adipiscing commodo elit at. Netus et malesuada fames ac. Lacus luctus accumsan tortor posuere ac ut consequat semper. Facilisis volutpat est velit egestas dui. Dolor magna eget est lorem. Integer vitae justo eget magna fermentum. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Faucibus in ornare quam viverra orci. Mauris in aliquam sem fringilla. Ac turpis egestas integer eget aliquet nibh praesent. Massa tempor nec feugiat nisl pretium. Congue eu consequat ac felis donec et odio pellentesque diam. Viverra orci sagittis eu volutpat odio. Risus nec feugiat in fermentum. Blandit aliquam etiam erat velit scelerisque in dictum. Suspendisse faucibus interdum posuere lorem ipsum dolor. Massa tincidunt nunc pulvinar sapien et ligula. Diam phasellus vestibulum lorem sed risus. Nisi lacus sed viverra tellus in hac habitasse. Lectus magna fringilla urna porttitor rhoncus dolor purus non enim.'
}